name: Release
on:
  release:
    types: [published]
jobs:
  release_213:
    name: Release 2.13
    runs-on: ubuntu-20.04
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Install Java And Sbt
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Setup Gpg
        uses: olafurpg/setup-gpg@v3
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            $HOME/.cache/coursier
            $HOME/.ivy2/cache
            $HOME/.sbt/boot/
            $HOME/.sbt
            lib_managed
            target
            project/target
          key: ${{ runner.os }}-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}
      - name: Release for Scala 2.13
        run: CI_RELEASE=publishSigned sbt ++2.13.15 releaseIt
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  release_3:
    name: Release 3
    needs: release_213
    runs-on: ubuntu-20.04
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Install Java And Sbt
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Setup Gpg
        uses: olafurpg/setup-gpg@v3
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            $HOME/.cache/coursier
            $HOME/.ivy2/cache
            $HOME/.sbt/boot/
            $HOME/.sbt
            lib_managed
            target
            project/target
          key: ${{ runner.os }}-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}
      - name: Release for Scala 3
        run: CI_RELEASE=publishSigned sbt ++3.3.4 releaseIt
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
